### ISSUE TITLE
Pyinstaller cannot find PyQt5 plugin  AND Paths checked: C:/Qt/5.6.0/plugins

### ISSUE THREAD

**Issue by francopythonss** [francopythonss/Pyinstaller-cannot-find-PyQt5-Help#1]
Hi can anybody help me please!.. 
I have windows 8.1
Python 3.5
Pyqt5 installed with pip
sip installed with pip

C:\Users\mario\Desktop\Nueva carpeta>pyinstaller proyecto.py
129 INFO: PyInstaller: 3.4
129 INFO: Python: 3.5.0
129 INFO: Platform: Windows-10.0.17134
129 INFO: wrote C:\Users\mario\Desktop\Nueva carpeta\proyecto.spec
129 INFO: UPX is not available.
145 INFO: Extending PYTHONPATH with paths
['C:\\Users\\mario\\Desktop\\Nueva carpeta',
 'C:\\Users\\mario\\Desktop\\Nueva carpeta']
145 INFO: checking Analysis
145 INFO: Building Analysis because Analysis-00.toc is non existent
145 INFO: Initializing module dependency graph...
145 INFO: Initializing module graph hooks...
145 INFO: Analyzing base_library.zip ...
4248 INFO: running Analysis Analysis-00.toc
4295 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python.exe
4342 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python.exe
4373 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python.exe
4404 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python.exe
4451 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python.exe
4607 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4638 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4685 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4716 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4748 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4795 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4826 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4857 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4908 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4935 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
4966 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
5013 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\python35.dll
5059 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\VCRUNTIME140.dll
5091 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\VCRUNTIME140.dll
5122 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\VCRUNTIME140.dll
5170 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\VCRUNTIME140.dll
5203 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\mario\appdata\local\programs\python\python35\VCRUNTIME140.dll
5203 INFO: Caching module hooks...
5218 INFO: Analyzing C:\Users\mario\Desktop\Nueva carpeta\proyecto.py
6357 INFO: Loading module hooks...
6357 INFO: Loading module hook "hook-PyQt5.py"...
6575 INFO: Loading module hook "hook-PIL.Image.py"...
6763 INFO: Processing pre-find module path hook   distutils
7105 INFO: Loading module hook "hook-xml.py"...
7402 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
7839 WARNING: Unable to find Qt5 translations C:/Qt/5.6.0/translations\qtbase_*.qm. These translations were not packaged.
7839 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
Traceback (most recent call last):
  File "C:\Users\mario\AppData\Local\Programs\Python\Python35\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 514, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\users\mario\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 117, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/Qt/5.6.0/plugins

**Comment by francopythonss** [comment]
@ bjones1

**Comment by francopythonss** [comment]
@bjones1

**Comment by bjones1** [comment]
Try using the latest development version of PyInstaller and see if that fixes it. There's a patch for PyQt5 on Anaconda that might help.

**Comment by francopythonss** [comment]
Pyinstaller version is 3.4 .. 
Could you tell me the steps to install that patch please. I install anaconda full?
@bjones1

**Comment by bjones1** [comment]
See https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version.

**Comment by francopythonss** [comment]
Thankss!!! @bjones1

**Comment by francopythonss** [comment]
I'm new to this and I can not make this happen, could you help me with this?
pyi-makespec --paths=/path/to/thisdir \
             --paths=/path/to/otherdir myscript.py  ??
@bjones1

**Comment by bjones1** [comment]
Sorry, I've got lots of other things to work on. Please read the excellent manual.

**Comment by francopythonss** [comment]
> Lo siento, tengo muchas otras cosas para trabajar. Por favor, lea el excelente manual.


I'll keep trying, sorry for the inconvenience, I'm an amateur

**Comment by francopythonss** [comment]
Hi Bryan, I was able to solve the problem, thanks for your help. I had another problem, if you could give me a hand I would appreciate it
@bjones1

**Comment by francopythonss** [comment]
import pyautogui
# mouseNow.py

x, y = pyautogui.position()

positionStr = 'X: ' + str(x).rjust(4) + ' Y: ' + str(y).rjust(4)
pixelColor = pyautogui.screenshot().getpixel((x, y))


positionStr += ' RGB: (' + str(pixelColor[0]).rjust(3)
positionStr += ', ' + str(pixelColor[1]).rjust(3)
positionStr += ', ' + str(pixelColor[2]).rjust(3) + ')'

while pixelColor > pixelColor[84]:
    if pixelColor < pixelColor[84]:
        pyautogui.keyDown('x')

    else:
        print ("ok")

IndexError: tuple index out of range
